version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  # Specify the Python version you need
      terraform: 1.0.0  # Specify the Terraform version you need
    commands:
      - echo "Installing required dependencies..."
      - pip install --upgrade pip
      - pip install pre-commit  # If you're using pre-commit for linting
      - apt-get update && apt-get install -y opa  # Install OPA
      - terraform init  # Initialize Terraform

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      - terraform validate  # Validate Terraform configuration

  build:
    commands:
      - echo "Running Terraform plan..."
      - terraform plan -out=tfplan
      - echo "Evaluating policy with OPA..."
      - opa eval --input tfplan --data policy.rego "data.terraform.s3.deny"  # Check policy

  post_build:
    commands:
      - echo "Applying Terraform changes..."
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - ~/.terraform/plugins
