version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      - unzip terraform.zip
      - sudo mv terraform /usr/local/bin/
      - terraform --version
      - echo Installing OPA...
      - curl -Lo opa https://github.com/open-policy-agent/opa/releases/latest/download/opa_linux_amd64
      - chmod +x opa
      - sudo mv opa /usr/local/bin/
      - opa version
  pre_build:
    commands:
      - echo Logging in to AWS...
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set default.region $AWS_DEFAULT_REGION
  build:
    commands:
      - echo Starting Terraform...
      - terraform init
      - terraform validate
      - terraform plan -out=tfplan
      - echo Showing Terraform plan...
      - terraform show tfplan
      - echo Generating JSON output from tfplan...
      - terraform show -json tfplan > tfplan.json
      - echo Showing the content of tfplan.json...
      - cat tfplan.json
      - echo Evaluating policy with OPA...
      - |
        opa eval --data policy.rego --input tfplan.json "data.example.s3.violation" || { 
          echo "OPA evaluation failed: Policy violation detected"; 
          exit 1; 
        }
 
  post_build:
    commands:
      - echo Applying Terraform plan...
      - terraform apply -auto-approve tfplan || { echo "Terraform apply failed"; exit 1; }
