version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform"
      - LATEST_TERRAFORM_VERSION=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r .current_version)
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/${LATEST_TERRAFORM_VERSION}/terraform_${LATEST_TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform.zip
      - sudo mv terraform /usr/local/bin/
      - terraform --version

  build:
    commands:
      - echo "Build phase: Running Terraform Plan"
      - terraform plan -out=tfplan
      - terraform show -json tfplan > tfplan.json
      - echo "Evaluating OPA policy against Terraform plan"
      - |
        OPA_RESULT=$(opa eval --data policy.rego --input tfplan.json "data.terraform.s3.deny" -o json)
        echo "$OPA_RESULT"
        if echo "$OPA_RESULT" | jq -e '.result[0].expressions[0].value == true' > /dev/null; then
            echo "Policy violation: S3 bucket tag modification is not allowed."
            exit 1
        else
            echo "Policy check passed."
        fi

  post_build:
    commands:
      - echo "Post-build phase"
      - echo "Build completed successfully on `date`"
