version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform..."
      - curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - chmod +x /usr/local/bin/terraform

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init  # Ensure Terraform is initialized
      - echo "Running pre-build steps..."
      - terraform validate  # Validate Terraform configuration

  build:
    commands:
      - echo "Running Terraform plan..."
      - terraform plan -out=tfplan
      - echo "Evaluating policy with OPA..."
      - opa eval --input tfplan --data policy.rego "data.terraform.s3.deny"

  post_build:
    commands:
      - echo "Applying Terraform changes..."
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - ~/.terraform/plugins
